basePath: /api
definitions:
  basic.Vendor:
    type: object
  errcode.Error:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  service.AuthRequest:
    properties:
      app_key:
        type: string
      app_secret:
        type: string
    required:
    - app_key
    - app_secret
    type: object
  service.CreateVendorRequest:
    properties:
      name:
        type: string
      uuid:
        type: integer
    required:
    - name
    type: object
  service.UpdateVendorRequest:
    properties:
      id:
        type: integer
      name:
        type: string
      uuid:
        type: integer
    required:
    - id
    type: object
info:
  contact: {}
  description: This is a potato use golang
  title: Potato Api
  version: "1.0"
paths:
  /v1/auth:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Vendor模型
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 用户验证
  /v1/vendors:
    get:
      consumes:
      - application/json
      parameters:
      - description: auth by /auth
        in: header
        name: token
        required: true
        type: string
      - description: 名称
        in: query
        maxLength: 100
        name: name
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/basic.Vendor'
      summary: 系统厂商列表
      tags:
      - vendors
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: auth by /auth
        in: header
        name: token
        required: true
        type: string
      - description: Vendor模型
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.CreateVendorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/basic.Vendor'
      summary: 新增系统厂商
      tags:
      - vendors
  /v1/vendors/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: auth by /auth
        in: header
        name: token
        required: true
        type: string
      - description: 系统厂商 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/basic.Vendor'
      summary: 删除系统厂商
      tags:
      - vendors
    patch:
      consumes:
      - multipart/form-data
      parameters:
      - description: auth by /auth
        in: header
        name: token
        required: true
        type: string
      - description: 系统厂商 ID
        in: path
        name: id
        required: true
        type: integer
      - description: Vendor模型
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.UpdateVendorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/basic.Vendor'
      summary: 修改系统厂商
      tags:
      - vendors
swagger: "2.0"
